# ____    _  __ __   __  ____    _        ___     ____   _  __ 
#/ ___|  | |/ / \ \ / / | __ )  | |      / _ \   / ___| | |/ / 
#\___ \  | ' /   \ V /  |  _ \  | |     | | | | | |     | ' /  
# ___) | | . \    | |   | |_) | | |___  | |_| | | |___  | . \  
#|____/  |_|\_\   |_|   |____/  |_____|  \___/   \____| |_|\_\
#
#
#               ____   _   _   ___      __  _   _   ___  
#              / ___| | | | | |_ _|    / / | | | | |_ _| 
#             | |  _  | | | |  | |    / /  | | | |  | |  
#             | |_| | | |_| |  | |   / /   | |_| |  | |  
#              \____|  \___/  |___| /_/     \___/  |___|
#
#                        _               
#                       | |__    _   _  
#                       | '_ \  | | | | 
#                       | |_) | | |_| | 
#                       |_.__/   \__, | 
#                                 |___/
#
# _____                  ____    _                 _    
#|_   _| | |__     ___  | __ )  | |   __ _   ___  | |_    
#  | |   | '_ \   / _ \ |  _ \  | |  / _` | / __| | __| 
#  | |   | | | | |  __/ | |_) | | | | (_| | \__ \ | |_  
#  |_|   |_| |_|  \___| |____/  |_|  \__,_| |___/  \__|

Option: "Ui"

#      ____   _   _   ___  
#     / ___| | | | | |_ _| 
#    | |  _  | | | |  | |  
#    | |_| | | |_| |  | |  
#     \____|  \___/  |___|

Island-Creation-Gui-Menu-Name: "Choose one!"

Create-Island-Gui-Item-Name: "Create Island"
Item-id-1: "1"
Item-meta-1: "0"
Item-Slot-1: "1"

Accept-Invite-Gui-Item-Name: "Accept Invite"
Item-id-2: "1"
Item-meta-2: "5"
Item-Slot-2: "2"

Choose-Island-Gui-Menu-Name: "Choose an Island"

Basic-Island-Gui-Item-Name: "Basic Island"
Item-id-3: "1"
Item-meta-3: "0"
Item-Slot-3: "1"

Palm-Island-Gui-Item-Name: "Palm Island"
Item-id-4: "1"
Item-meta-4: "0"
Item-Slot-4: "2"

Shelly-Island-Gui-Item-Name: "Shelly Island"
Item-id-5: "1"
Item-meta-5: "0"
Item-Slot-5: "3"

Op-Island-Gui-Item-Name: "Op Island"
Item-id-6: "1"
Item-meta-6: "0"
Item-Slot-6: "4"

Lost-Island-Gui-Item-Name: "Lost Island"
Item-id-7: "1"
Item-meta-7: "0"
Item-Slot-7: "5"

Island-Management-Gui-Menu-Name: "Management"

Manage-Members-Gui-Item-Name: "Manage Members"
Item-id-8: "1"
Item-meta-8: "0"
Item-Slot-8: "1"

Manage-Island-Gui-Item-Name: "Manage Island"
Item-id-9: "1"
Item-meta-9: "0"
Item-Slot-9: "2"

Warning-Area-Island-Gui-Item-Name: "Warning Area!"
Item-id-10: "1"
Item-meta-10: "0"
Item-Slot-10: "3"

Management-Members-Gui-Menu-Name: "Manage Members"

Cooperate-Members-Gui-Item-Name: "Cooperate"
Item-id-11: "1"
Item-meta-11: "0"
Item-Slot-11: "1"

Promote-Members-Gui-Item-Name: "Promote"
Item-id-12: "1"
Item-meta-12: "0"
Item-Slot-12: "2"

Demote-Members-Gui-Item-Name: "Demote"
Item-id-13: "1"
Item-meta-13: "0"
Item-Slot-13: "3"

Banish-Members-Gui-Item-Name: "Banish"
Item-id-14: "1"
Item-meta-14: "0"
Item-Slot-14: "4"

Fire-Members-Gui-Item-Name: "Fire"
Item-id-15: "1"
Item-meta-15: "0"
Item-Slot-15: "5"

Members-Members-Gui-Item-Name: "Members"
Item-id-16: "1"
Item-meta-16: "0"
Item-Slot-16: "6"

Management-Island-Gui-Menu-Name: "Manage Island"

Join-Island-Gui-Item-Name: "join"
Item-id-17: "1"
Item-meta-17: "0"
Item-Slot-17: "1"

Lock-Island-Gui-Item-Name: "Lock"
Item-id-18: "1"
Item-meta-18: "0"
Item-Slot-18: "2"

Chat-Island-Gui-Item-Name: "Chat"
Item-id-19: "1"
Item-meta-19: "0"
Item-Slot-19: "3"

Setspawn-Island-Gui-Item-Name: "Setspawn"
Item-id-20: "1"
Item-meta-20: "0"
Item-Slot-20: "4"

Category-Island-Gui-Item-Name: "Category"
Item-id-21: "1"
Item-meta-21: "0"
Item-Slot-21: "5"

Blocks-Island-Gui-Item-Name: "Blocks"
Item-id-22: "1"
Item-meta-22: "0"
Item-Slot-22: "6"

Visit-Island-Gui-Item-Name: "Visit"
Item-id-23: "1"
Item-meta-23: "0"
Item-Slot-23: "7"

Help-Island-Gui-Name: "Help"
Item-id-24: "1"
Item-meta-24: "0"
Item-Slot-24: "8"

Management-Warning-Gui-Menu-Name: "Warning area!!"

Transfer-Warning-Gui-Item-Name: "Transfer"
Item-id-25: "1"
Item-meta-25: "0"
Item-Slot-25: "1"

Disband-Warning-Gui-Item-Name: "disband"
Item-id-26: "1"
Item-meta-26: "0"
Item-Slot-26: "2"



#    _   _   ___  
#   | | | | |_ _| 
#   | | | |  | |  
#   | |_| |  | |  
#    \___/  |___|

Island-Creation-Ui-Menu-Name: "Create Island"

Island-Creation-Ui-Content: "Choose one!"

Create-Island-Ui-Button-Name: "Create an Island"

Accept-Invite-Ui-Button-Name: "Accept Invite"

